### ISSUE TITLE
Question about Restore 

### ISSUE THREAD

**Issue by tabbi** [thelastpickle/cassandra-medusa#191]
Hello! in the performing backup section in Wiki, it says that **All Medusa backups only copy new SSTables from the nodes**

and in the restore scenario (if we restore data to the same cluster  it says ( Delete the commit log, saved caches and data directory including system keyspaces) 
so my question is, for what differential backups is exist? if i restore from differential backup i only restore keyspaces that exist on this differential backup? keyspaces which not changed before differential backup didn't restored?
sorry for my bad english

**Comment by tabbi** [comment]
@adejanovski and what will do, if i for example, purge all the backups ( except the last differential) and clear the cassandra node, and restore from this backup? is it right to make a for example 2 differential backups, and 1 full backup every day on the cassandra production cluster?
thanks a lot

**Comment by adejanovski** [comment]
Each backup manifest file will point to the sstables that are part of this backup in the data folder.
When an old differential backup is deleted, its manifest gets deleted and the data folder gets purged from files that don't appear in any of the remaining backups manifest.
So even if you delete all prior differentials, then the last one will still have all the sstables that it's supposed to have so that the backup isn't missing anything that would be required to perform a full restore.

Either run differential or full backups, but there's no need to run both.

**Comment by tabbi** [comment]
@adejanovski sorry i'm dumb, but for what the full backups exist?

**Comment by adejanovski** [comment]
It's not a dumb question :)
Medusa was built initially only with full backups. Differential backups were introduced later.
I'm in favor of deprecating full backups and keeping differential backups only.

**Comment by tabbi** [comment]
@adejanovski Thank you so much for the answer! im watching you on YouTube right now, you a very smart and kind man!
thanks a lot dude!

**Comment by arodrime** [comment]
@tabbi closing this.

You're right about Alex ;-).

Feel free to join channel #cassandra-medusa in ASF slack [http://s.apache.org/slack-invite](http://s.apache.org/slack-invite) for more talking :)
