### ISSUE TITLE
s3_compatible storage and region parameter

### ISSUE THREAD

**Issue by Skunnyk** [thelastpickle/cassandra-medusa#301]
The new version 0.9.0 support `s3_compatible` storage, this is a good new.
However, I can't figure out how to configure it correctly to upload to a s3 compatible endpoint (for example, I use OVHcloud s3 object storage api).

It looks like the `region` parameter is not passed to libcloud/minio driver.

If I edit my installed `libcloud/storage/drivers/minio.py` to hardcode `region_name = "gra"` as indicated in https://github.com/thelastpickle/cassandra-medusa/pull/272#discussion_r569258766 + https://github.com/apache/libcloud/issues/1539#issuecomment-754661526, everything is working, I can backup/list etc

My configuration:
```
[storage]
storage_provider = s3_compatible
host = s3.gra.cloud.ovh.net
bucket_name = mybucket
region = gra
key_file = /etc/medusa/credentials-s3
```

Am I missing something ? Also, the wiki does not document the new s3_compatible feature :)

Thank you !

**Comment by adejanovski** [comment]
Hi @Skunnyk,

Your analysis is right,  Libcloud [doesn't set the region](https://github.com/apache/libcloud/blob/4370a7021c11c1c61afe6470d2baafc093bfa0dd/libcloud/storage/drivers/minio.py#L49) in the MinIO driver which is what we use as base for the S3 compatible storage :'(

@burmanm, I think we should use our own implementation of the MinIO Libcloud driver which passes the region properly. wdyt?
We could also send a PR to Libcloud in order to get that supported, but I'm not sure the MinIO driver is supposed to pass a region and it's on us to carry the fact that we're using it as base driver for our S3 compatible implementation.

**Comment by burmanm** [comment]
Well, Minio itself supports regions, so I guess the driver should as well. But we can do our own base implemention, less dependencies we have to libcloud, the better in my opinion.

**Comment by Skunnyk** [comment]
Cool, I confirm that #304 is working for me :)

**Comment by adejanovski** [comment]
Thanks for confirming this @Skunnyk 🙏
