### ISSUE TITLE
Restore cluster from S3 on remote cluster

### ISSUE THREAD

**Issue by alvaropalmeirao** [thelastpickle/cassandra-medusa#325]
Hi all,

I have a question. Imagine that my cluster was destroyed but I have my backups on S3. Then I install a new cluster with the same number of nodes. I realized that medusa only restores a full cluster but remotely. Since my former cluster is gone how can I restore a new cluster from s3 backups?

Thanks.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-205) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-205

**Comment by adejanovski** [comment]
Hi, 

you just have to install Medusa on each node in the new cluster and configure it so that it has access to the S3 bucket that contains the backups. 
List your backups using `medusa list-backups --show-all`  (the `--show-all` flag will allow you to list backups that didn't involve the current node), and then restore the one you choose to as you would've done on the initial cluster: `medusa restore-cluster --backup-name=<name of the backup>`.

Medusa will map backups with each node and enforce the tokens by modifying `cassandra.yaml` files, then bootstrap the cluster appropriately.

**Comment by alvaropalmeirao** [comment]
Ok, i've made that but i got the following errors after 10 mins:
```
[2021-04-07 16:10:28,991] ERROR: Some nodes failed to restore. Exiting
[2021-04-07 16:10:28,991] ERROR: This error happened during the cluster restore: Some nodes failed to restore. Exiting
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/medusa/restore_cluster.py", line 69, in orchestrate
    restore.execute()
  File "/usr/local/lib/python3.5/dist-packages/medusa/restore_cluster.py", line 144, in execute
    self._restore_data()
  File "/usr/local/lib/python3.5/dist-packages/medusa/restore_cluster.py", line 386, in _restore_data
    raise Exception(err_msg)
Exception: Some nodes failed to restore. Exiting
```

Where can I troubleshoot this error?

**Comment by alvaropalmeirao** [comment]
New info: 
The medusa had that error but all medusa processes on the remote nodes had continued and I think the restore was successful. I see the my keyspaces and my data. So what do you think it happened?

**Comment by m934030039** [comment]
> 9029e8bac61a && medusa-wrapper sudo

You can use the full path of medusa-wrapper and try.

e.g.  # vim /usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py ( To use full path of the command on all nodes)
368         command = 'nohup /usr/bin/bash -c "mkdir {work}; cd {work} && /usr/local/bin/medusa-wrapper sudo /usr/local/bin/medusa --fqdn=%s -vvv restore-node ' \
369                   '{in_place} {keep_auth} %s {verify} --backup-name {backup} --temp-dir {temp_dir} ' \
370                   '{use_sstableloader} {keyspaces} {tables}"' \
