### ISSUE TITLE
gRPC operations enhancement for taking backups

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-medusa#376]
The `doBackup()` operation is a blocking one which waits for the backup to be finished before returning.
As backups can take hours to complete, it doesn't seem like the most solid way to achieve this.
We should rather make the `doBackup()` operation start a thread that will perform the backup and return an id (or just a status code, thinking out loud here) that will be used to track progress through a newly created operation.
Checking the state of the backup will be done by checking the return code of the thread.

┆Issue is synchronized with this [Jira Feature](https://k8ssandra.atlassian.net/browse/K8SSAND-628) by [Unito](https://www.unito.io)
┆Reviewer: Alexander Dejanovski
┆epic: Remote Cluster Restore
┆friendlyId: K8SSAND-628
┆priority: Medium

**Comment by jsanda** [comment]
>The doBackup() operation is a blocking one which waits for the backup to be finished before returning.
As backups can take hours to complete, it doesn't seem like the most solid way to achieve this.

At the risk of adding confusion I believe the underlying network call is actually non-blocking. The Go runtime will switch execution to another goroutine. If there is only a single underlying thread that is running goroutines, the Go runtime will continue running other goroutines.

Now with respect to the gRPC call it absolutely is blocking, and I agree 💯 that it would be better do this asynchronously such that this method becomes more of a scheduling operation that adds the task to a thread pool queue on the Medusa side.

Here is the first thing that happens in `cassandrabackup_controller.go` after fetching the CassandraBackup object:

```go
	// If there is anything in progress, simply requeue the request
	if len(backup.Status.InProgress) > 0 {
		r.Log.Info("CassandraBackup is being processed already", "Backup", req.NamespacedName)
		return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
	}
```

This check is problematic IMO. We should be calling Medusa to get the actual status of the backup operation and then update the CassandraBackup status accordingly.

I am not sure how we could end up in a situation where we fail to update the status in the current code, but that is exactly what looks like happened in @adejanovski's environment.

Here is one way if definitely could happen. The backup operation is in progress and the medusa-operator pod gets terminated. The deployment controller will create a new medusa-operator pod. The CassandraBackup status won't get updated because of the above check.
