### ISSUE TITLE
AWS S3 region eu-south-1 not supported

### ISSUE THREAD

**Issue by mug3n451** [thelastpickle/cassandra-medusa#556]
Hi,
i'm writing to ask if it's possible add the compatibility of medusa with the s3 region eu-south-1, seen this region already exists from long time and is used by italian IT company for their projects

thank you very much
Cristian

**Comment by adejanovski** [comment]
Hi, it is supported already. Just use `s3` as `storage_provider` and set the `region` setting to `eu-south-1`.

**Comment by mug3n451** [comment]
Hi and thanks for the replay. 
I'm using medusa as a container image on k8ssandra project. the version of medusa container is 0.13.4 and i have this error during the deployment:

`
ValueError: Invalid or unsupported region: eu-south-1
`
thanks

**Comment by burmanm** [comment]
This is actually a real issue in the libcloud version we use, since it tries to validate the region values that are allowed:

https://github.com/apache/libcloud/blob/d163f9ba5938aff7d23dec72fa549a482f6836c7/libcloud/storage/drivers/s3.py#L1243


And "eu-south-1" is not in the list: 

https://github.com/apache/libcloud/blob/d163f9ba5938aff7d23dec72fa549a482f6836c7/libcloud/storage/drivers/s3.py#L84

I'm not sure if using s3_rgw works against s3 (it might require some manual work), but otherwise libcloud is blocking our access.

**Comment by rzvoncek** [comment]
We no longer use libcloud, it got replaced by boto3. I'm pretty sure we support all the regions now (since v0.16.1), not just the one libcloud does. I'll go ahead and close this. Please open a new issue if still facing problems.
