### ISSUE TITLE
Restore Cluster from S3 crashes and re-run cluster restore

### ISSUE THREAD

**Issue by dmirallestl** [thelastpickle/cassandra-medusa#557]
Hi! 

I have a question, we've an specific scenario in which we've a cluster of 3 nodes. When restoring or syncing nodes from incremental backup, we're getting crashes and data is completely lost. 

- How is medusa managing this scenario? 
- What happens if incremental backup restore crashes and another one is triggered? 
- Data not restored is completely lost and only incremental backup is restored?

Thanks!

**Comment by adejanovski** [comment]
> When restoring or syncing nodes from incremental backup, we're getting crashes and data is completely lost.

Do you mean differential backups?

> How is medusa managing this scenario?

There's no management for recovering from a crash during a restore in medusa.

> What happens if incremental backup restore crashes and another one is triggered?

If another restore is attempted, it'll start from scratch and re-download the whole dataset.

> Data not restored is completely lost and only incremental backup is restored?

Restores are never partial, they will restore all the expected data, not just the data that was uploaded in the last differential backups (if indeed we're talking about this).

In case the restore orchestration cannot work anymore because the nodes fail to start, you can invoke the `medusa restore-node` command directly on each node to restore them individually, even if they are unable to start.
Make sure you use the right settings though when invoking that command (especially the `in-place` and `keep-auth` ones).

**Comment by burmanm** [comment]
Closing this ticket as answered. If you have further questions, please reopen.
