### ISSUE TITLE
MD5 hash  checksum does not match

### ISSUE THREAD

**Issue by nicholasamorim** [thelastpickle/cassandra-medusa#58]
I'm trying to backup a 6-node cluster and this keeps happening.

3 nodes out of 6 finish fine but 3 always fail (apparently random machines).

The failed ones contain logs like this:

```
[2020-01-21 09:04:12,816] INFO: Uploading /cassandradb/data/sm_scotia/activity_v2-e1dbfa20f27b11e9b97a75eb25aa986a/snapshots/medusa-3943bf26-f320-4bd9-8637-013b06ec4ffa/md-118609-big-Statistics.db (17.950KiB)
[2020-01-21 09:04:12,878] DEBUG: Cleaning up snapshot
[2020-01-21 09:04:12,878] DEBUG: Executing: nodetool clearsnapshot -t medusa-3943bf26-f320-4bd9-8637-013b06ec4ffa
[2020-01-21 09:04:14,734] DEBUG: nodetool output: Requested clearing snapshot(s) for [all keyspaces] with snapshot name [medusa-3943bf26-f320-4bd9-8637-013b06ec4ffa]

[2020-01-21 09:04:14,735] ERROR: This error happened during the backup: <ObjectHashMismatchError in <libcloud.storage.drivers.rgw.S3RGWStorageDriver object at 0x7f82608ec190>, value=MD5 hash  checksum does not match 729db185d04fb6a33c6b231c9d09a215, object = pf-ca1-cc3/data/sm_scotia/activity_v2-e1dbfa20f27b11e9b97a75eb25aa986a/md-108464-big-Data.db>
```

Any tips or reasoning for this? Log level is already debug so there's not more info than that.

**Comment by adejanovski** [comment]
From what I can see [in the code](https://github.com/apache/libcloud/blob/acb9a955c2/libcloud/storage/drivers/s3.py#L856-L860), libcloud will check the hash returned by the storage server after an upload, and compare it to a locally computed hash. In your case, based on the error message, the server didn't return any hash that libcloud could use (there should be something between `MD5 hash` and `checksum does...`).

It could be that your storage backend (which is CEPH if I remember correctly) does something special on large files when it comes to computing hashes (something similar to S3 and multi part uploads), or just that something actually went wrong with the upload (transient errors).
The fact that the issue happens randomly points to the latter rather than the former.
We already retry the uploads several times before giving up, so it's odd that we get random errors like this: https://github.com/thelastpickle/cassandra-medusa/blob/5c4ea59d9414e840f04a54a642de1948f16cec10/medusa/storage/concurrent.py#L104-L112

You could try disabling the hash check by adding `verify_hash=False` to the `upload_object()` call here : https://github.com/thelastpickle/cassandra-medusa/blob/5c4ea59d9414e840f04a54a642de1948f16cec10/medusa/storage/concurrent.py#L106-L110

FTR, `verify_hash` is set to `False` when using `upload_object_via_stream()` instead of `upload_object()`: https://github.com/apache/libcloud/blob/acb9a955c2/libcloud/storage/drivers/s3.py#L691
I've thought for a while that we should rather rely on `upload_object_via_stream()` to avoid memory issues anyway.
So maybe we could fix the issue (or an underlying one) by removing `upload_object()` calls and upload them via stream.

wdyt?

**Comment by nicholasamorim** [comment]
@adejanovski We've disabled replication in Ceph as a first (and most obvious change recently) test. If that doesn't solve it, I'll create a branch and I'll test it using the `upload_object_via_stream`.

If that works, I'll be opening a PR soon. Thank you very much for looking into this!

**Comment by nicholasamorim** [comment]
@adejanovski so far the change has been successful. It's been doing the first full backup for many hours without stopping (unlike using `upload_object` that was taking only a couple hours and then stopping).

You can see the change [here](https://github.com/nicholasamorim/cassandra-medusa/commit/f23532c699eb73f0ebdadf31f9a02e9c7827eba2) - as expected, it's dead simple.

I'm still doing tests, but I have a question. libcloud [documentation states](https://libcloud.readthedocs.io/en/stable/storage/api.html#libcloud.storage.base.StorageDriver.upload_object_via_stream) that if the backend _does not_ implement the stream, it will _transparently_ call the `upload_object` and this can be very problematic because it will exhaust the iterator and load the whole thing in memory. Here's an [example](https://libcloud.readthedocs.io/en/stable/_modules/libcloud/storage/drivers/backblaze_b2.html#BackblazeB2StorageDriver.upload_object_via_stream).

libcloud does not provide a way to detect if the backend supports or not. Should we adopt a `whitelist` approach and use `_via_stream` only for S3 and GCP at first?

**Comment by adejanovski** [comment]
Hi @nicholasamorim,

nice, it's a good thing that the change is both simple and efficient.
There is not much we can do about the backends that don't support streams, as we have no workaround anyway. Currently, we're only supporting S3, GCS, local and CEPH. S3 and GCS both bypass libcloud for uploads/downloads currently, using awscli and gsutil respectively. The other two do support streams so we're fine.
Since we'll be uploading multi GBs (sometimes 100s of GB) files, we can't allow everything to be loaded into memory, and thus streams are the only valid way of dealing with this.

There's another thing that should be changed in concurrent.py, it's the downloads. I see it's still using `blob.download()`, which will not use streams and load everything into memory before writing the file to the local FS: https://github.com/nicholasamorim/cassandra-medusa/blob/f23532c699eb73f0ebdadf31f9a02e9c7827eba2/medusa/storage/concurrent.py#L133-L154

Do you think you can handle this in the same PR?
That would be greatly appreciated!

**Comment by arodrime** [comment]
This issue seems to have been sorted out and fixed. It was not much of a MD5 issue but rather an issue with uploads failing (because not using streams).

If this is still a problem, please re-open
