### ISSUE TITLE
Backing up to OCI buckets

### ISSUE THREAD

**Issue by MariusMRex** [thelastpickle/cassandra-medusa#702]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=49597011)

Does cassandra-medusa support backing up to Oracle Cloud Infrastructure buckets?  I assume it can be done through the s3_compatible storage provider.    If OCI buckets are supported, at what release of cassandra-medusa is this supported under?  I see that the the use of boto3 was included as part of release 0.16, but currently our organization's python version does not support the necessary dependencies.  This is why we are looking at an earlier release of cassandra-medusa.  Assuming I can get this working with OCI buckets I would be happy to submit a patch to the documentation for inclusion with this project.

I am also in consultation with datastax support to investigate this issue specifically from the cassandra side.

**Comment by rzvoncek** [comment]
Hi @MariusMRex!

Yes, anything that talks the S3 protocol can be used under the `s3_compatible` umbrella. Otherwise, you'd need to make your own implementation of the [AbstractStorage](https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/storage/abstract_storage.py). It shouldn't be too hard as the only thing you'd need to do is implement the primitive operations of manipulating blobs. Then wire it into the config, but that's rather simple.

What python version do you have to use? It might still be easy to go back to 3.7, but anything older than that would probably be really hard.

**Comment by MariusMRex** [comment]
@rzvoncek Thank you for your reply.   I now have it working.

The problem, in the end, was syntax in the medusa-s3-credentials file.  My native client, the OCI CLI, allows the use of optional quotes around values.   While I am using a different user/key  for cassandra medusa backups, I naturally coped the format over, quotes and all.  That format has been working for years on end, so I never gave it a second thought.  I just did not initially understand that the quotes were being passed as part of the aws_access_key_id and aws_secret_access_key.  Once I removed the extraneous " ", authentication succeeded and the backups proceeded without further issue.

**Comment by chrisjmiller1** [comment]
Hi @rzvoncek, 
I'm also trying to get Medusa working with OCI but getting a multipart upload error.
Can you share what version of Medusa you used and the contents of your medusa.ini (with obfuscated values)?
Thanks in advance,
Chris.
